config/routes.rb
Biblereading2::Application.routes.draw do
  resources :verses


  # authenticated :user do
  #   root :to => "verses#index"
  # end
  root :to => "verses#index"
  devise_for :users
  resources :users
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.has_role? :admin
      can :manage, :all
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :role_ids, :as => :admin
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me
  
end

app/models/verse.rb
class Verse < ActiveRecord::Base
  attr_accessible :gospel, :letters, :old_test, :psalms_proverbs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_path, :alert => exception.message
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @users = User.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    authorize! :index, @user, :message => 'Not authorized as an administrator.'
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
  
  def update
    authorize! :update, @user, :message => 'Not authorized as an administrator.'
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user], :as => :admin)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end
    
  def destroy
    authorize! :destroy, @user, :message => 'Not authorized as an administrator.'
    user = User.find(params[:id])
    unless user == current_user
      user.destroy
      redirect_to users_path, :notice => "User deleted."
    else
      redirect_to users_path, :notice => "Can't delete yourself."
    end
  end
end

app/controllers/verses_controller.rb
class VersesController < ApplicationController
  # GET /verses
  # GET /verses.json
  def index
    @verses = Verse.order(:id).page(params[:page])
    @preaddress = 'http://www.biblegateway.com/passage/?search='
    @postaddress = '&version=esv'


    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @verses }
    end
  end

  # GET /verses/1
  # GET /verses/1.json
  def show
    @verse = Verse.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @verse }
    end
  end

  # GET /verses/new
  # GET /verses/new.json
  def new
    @verse = Verse.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @verse }
    end
  end

  # GET /verses/1/edit
  def edit
    @verse = Verse.find(params[:id])
  end

  # POST /verses
  # POST /verses.json
  def create
    @verse = Verse.new(params[:verse])

    respond_to do |format|
      if @verse.save
        format.html { redirect_to @verse, notice: 'Verse was successfully created.' }
        format.json { render json: @verse, status: :created, location: @verse }
      else
        format.html { render action: "new" }
        format.json { render json: @verse.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /verses/1
  # PUT /verses/1.json
  def update
    @verse = Verse.find(params[:id])

    respond_to do |format|
      if @verse.update_attributes(params[:verse])
        format.html { redirect_to @verse, notice: 'Verse was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @verse.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /verses/1
  # DELETE /verses/1.json
  def destroy
    @verse = Verse.find(params[:id])
    @verse.destroy

    respond_to do |format|
      format.html { redirect_to verses_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def display_base_errors resource
    return '' if (resource.errors.empty?) or (resource.errors[:base].empty?)
    messages = resource.errors[:base].map { |msg| content_tag(:p, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-block">
      <button type="button" class="close" data-dismiss="alert">&#215;</button>
      #{messages}
    </div>
    HTML
    html.html_safe
  end
  
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/verses_helper.rb
module VersesHelper
end

app/views/home/index.html.haml
%h3 Home
- @users.each do |user|
  %p
    User: #{link_to user.name, user}

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
      %a.close{"data-dismiss" => "alert"} ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
= link_to "Bible Reading", root_path, :class => 'brand'
-#%ul.nav
-#  - if user_signed_in?
-#    %li
-#      = link_to 'Logout', destroy_user_session_path, :method=>'delete'
-#  - else
-#    %li
-#      = link_to 'Login', new_user_session_path
-#  - if user_signed_in?
-#    %li
-#      = link_to 'Edit account', edit_user_registration_path
-#    - if current_user.has_role? :admin
-#      %li
-#        = link_to 'Admin', users_path
-#  - else
-#    %li
-#      = link_to 'Sign up', new_user_registration_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
      %title= content_for?(:title) ? yield(:title) : "Biblereading2"
      %meta{:content => content_for?(:description) ? yield(:description) : "Biblereading2", :name => "description"}
        = stylesheet_link_tag "application", :media => "all"
        = javascript_include_tag "application"
        = csrf_meta_tags
        = yield(:head)
  %body{:class => "#{controller_name} #{action_name}"}
    %header.navbar.navbar-fixed-top
      %nav.navbar-inner
        .container
          = render 'layouts/navigation'
    #main{:role => "main"}
      .container
        .content
          .row
            .span12
              = render 'layouts/messages'
              = yield
          %footer
      / ! end of .container
    / ! end of #main

app/views/users/_user.html.haml
.modal{:id => "role-options-#{user.id}", :style => "display: none;"}
  = simple_form_for user, :url => user_path(user), :html => {:method => :put, :class => 'form-horizontal' } do |f|
    .modal-header
      %a.close{"data-dismiss" => "modal"} ×
      %h3 Change Role
    .modal-body
      = f.input :role_ids, :collection => Role.all, :as => :radio_buttons, :label_method => lambda {|t| t.name.titleize}, :label => false, :item_wrapper_class => 'inline'
    .modal-footer
      = f.submit "Change Role", :class => "btn"
      %a.btn{"data-dismiss" => "modal", :href => "#"} Close

app/views/users/index.html.haml
%h3 Users
.span8
  %table.table.table-condensed
    %thead
      %tr
        %th Username
        %th Email
        %th Registered
        %th Role
        %th
        %th
    %tbody
      - @users.each do |user|
        %tr
          %td= link_to user.name, user
          %td= user.email
          %td= user.created_at.to_date
          %td= user.roles.first.name.titleize unless user.roles.first.nil?
          %td
            %a.btn.btn-mini{"data-toggle" => "modal", :href => "#role-options-#{user.id}", :type => "button"} Change role
            = render user
          %td= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'btn btn-mini') unless user == current_user

app/views/users/show.html.haml
%h3 User
%p
  User: #{@user.name}
%p
  Email: #{@user.email if @user.email}

app/views/verses/_form.html.haml
= simple_form_for(@verse) do |f|
  = f.error_notification

  .form-inputs
    = f.input :gospel
    = f.input :letters
    = f.input :psalms_proverbs
    = f.input :old_test

  .form-actions
    = f.button :submit

app/views/verses/edit.html.haml
%h1 Editing verse

= render 'form'

= link_to 'Show', @verse
\|
= link_to 'Back', verses_path

app/views/verses/index.html.haml
%h2 Daily Bible Reading

= will_paginate @verses , previous_label: h("<"), next_label: h(">")

%table.table-striped.table-bordered.table-hover.table-condensed
  %tr
    %th #
    %th Gospels
    %th Letters
    %th Wisdom
    %th Old Testament

  - @verses.each do |verse|
    %tr
      %td= verse.id
      %td= verse.gospel
      %td= verse.letters
      %td= verse.psalms_proverbs
      %td= verse.old_test
      %td= link_to 'Read', @preaddress + verse.gospel + ';' + verse.letters + ';' + verse.psalms_proverbs + ';' + verse.old_test + @postaddress

= will_paginate @verses , previous_label: h("<"), next_label: h(">")

%br

app/views/verses/new.html.haml
%h1 New verse

= render 'form'

= link_to 'Back', verses_path

app/views/verses/show.html.haml
%p#notice= notice

%p
  %b Gospel:
  = @verse.gospel
%p
  %b Letters:
  = @verse.letters
%p
  %b Psalms proverbs:
  = @verse.psalms_proverbs
%p
  %b Old test:
  = @verse.old_test

= link_to 'Edit', edit_verse_path(@verse)
\|
= link_to 'Back', verses_path